// api/seller.js
//
// Vercel serverless function serving the public seller preview page at
// https://imbizohub.com/seller?id=<uuid>
//
// WHY THIS EXISTS (confirmed empirically, not assumed):
// The HTML itself is still generated by the Supabase edge function
// `seller-preview` — that stays the single source of truth for the
// markup and the Open Graph tags. This file exists purely to fix the
// response HEADERS, because two things were established by testing:
//
//   1. Opening the Supabase function URL directly in Chrome renders the
//      raw source rather than a page. Chrome wraps it in <pre>, which is
//      its signature for a `text/plain` response — so Supabase is not
//      honouring the `Content-Type: text/html` the function sets.
//   2. A Vercel `rewrite` proxying /seller to that function does NOT let
//      Vercel's own `headers` config override the proxied content type.
//      Adding a Content-Type header rule for /seller changed nothing.
//
// Together those meant the page could never render, and — more damaging
// — WhatsApp and Facebook scrapers would very likely refuse to read Open
// Graph tags out of a text/plain response, which defeats the entire
// point of the preview.
//
// A Vercel function has no such problem: it composes its own response,
// so the header it sets is the header the browser receives. It fetches
// the markup from the edge function and re-sends it with the correct
// type. No duplicated HTML, no Supabase keys needed here.
//
// NOTE: vercel.json's catch-all rule still applies
// X-Content-Type-Options: nosniff to this route. That is correct and
// wanted now that the type is right — but it is also precisely what
// turned the earlier bug from "renders slightly wrong" into "shows raw
// source", by forbidding the browser from sniffing its way out of a
// text/plain response. Worth remembering if this page ever regresses:
// check the Content-Type first, not the markup.

const SELLER_PREVIEW_URL =
  'https://goughfxpcwxwsfthlmii.supabase.co/functions/v1/seller-preview';

module.exports = async (req, res) => {
  try {
    // Accept the id from ?id= (the canonical share form) or from a
    // trailing path segment, so /seller/<uuid> style links keep working.
    let id = req.query && req.query.id ? String(req.query.id) : '';
    if (!id && req.url) {
      const path = req.url.split('?')[0];
      const last = path.split('/').filter(Boolean).pop();
      if (last && last !== 'seller') id = last;
    }

    const upstream = await fetch(
      `${SELLER_PREVIEW_URL}?id=${encodeURIComponent(id)}`,
      { headers: { Accept: 'text/html' } }
    );

    const html = await upstream.text();

    // The whole reason this file exists.
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Cache-Control', 'public, max-age=300, s-maxage=300');
    res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

    return res.status(upstream.status).send(html);
  } catch (err) {
    console.error('api/seller failed:', err);
    // Never leave a share link showing a raw stack trace — degrade to a
    // plain, correctly-typed page that still points somewhere useful.
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res
      .status(502)
      .send(
        '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">' +
          '<title>ImbizoHub</title><meta name="robots" content="noindex">' +
          '<style>body{background:#111;color:#fff;font-family:-apple-system,Roboto,Arial,sans-serif;' +
          'text-align:center;padding:48px 20px}a{color:#E8B44A}</style></head>' +
          '<body><h1>Something went wrong</h1>' +
          '<p>We could not load this profile just now.</p>' +
          '<p><a href="https://imbizohub.com">Go to ImbizoHub</a></p></body></html>'
      );
  }
};
