// api/seller.js
//
// Vercel serverless function serving the public seller preview page at
// https://imbizohub.com/seller?id=<uuid>
// and the short shop link at https://imbizohub.com/s/<slug>
//
// WHY THIS EXISTS (confirmed empirically, not assumed):
// The HTML itself is still generated by the Supabase edge function
// `seller-preview` — that stays the single source of truth for the
// markup and the Open Graph tags. This file exists purely to fix the
// response HEADERS, because two things were established by testing:
//
//   1. Opening the Supabase function URL directly in Chrome renders the
//      raw source rather than a page. Chrome wraps it in <pre>, which is
//      its signature for a `text/plain` response — so Supabase is not
//      honouring the `Content-Type: text/html` the function sets.
//   2. A Vercel `rewrite` proxying /seller to that function does NOT let
//      Vercel's own `headers` config override the proxied content type.
//      Adding a Content-Type header rule for /seller changed nothing.
//
// Together those meant the page could never render, and — more damaging
// — WhatsApp and Facebook scrapers would very likely refuse to read Open
// Graph tags out of a text/plain response, which defeats the entire
// point of the preview.
//
// A Vercel function has no such problem: it composes its own response,
// so the header it sets is the header the browser receives. It fetches
// the markup from the edge function and re-sends it with the correct
// type. No duplicated HTML, no Supabase keys needed here.
//
// NOTE: vercel.json's catch-all rule still applies
// X-Content-Type-Options: nosniff to this route. That is correct and
// wanted now that the type is right — but it is also precisely what
// turned the earlier bug from "renders slightly wrong" into "shows raw
// source", by forbidding the browser from sniffing its way out of a
// text/plain response. Worth remembering if this page ever regresses:
// check the Content-Type first, not the markup.

const SELLER_PREVIEW_URL =
  'https://goughfxpcwxwsfthlmii.supabase.co/functions/v1/seller-preview';

// A profile is addressable two ways: by uuid (what the app shares) and
// by slug (imbizohub.com/s/kombi-spares, what a Dealer Pro hands out).
// Both patterns are validated HERE as well as in the edge function —
// not duplication for its own sake: this file decides which query param
// to forward, and forwarding an unvalidated string would let a junk
// path segment become a database lookup, which is bug 2 in the edge
// function's own header, rediscovered one layer up.
const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const SLUG_RE = /^[a-z0-9][a-z0-9-]{1,28}[a-z0-9]$/;

module.exports = async (req, res) => {
  try {
    // ?slug= comes from the /s/:slug rewrite, ?id= from the canonical
    // share form. Path forms are still honoured for links already out in
    // the world — and for the case where a rewrite passes the path
    // through without populating req.query.
    const q = req.query || {};
    let id = q.id ? String(q.id).trim() : '';
    let slug = q.slug ? String(q.slug).trim().toLowerCase() : '';

    if (!UUID_RE.test(id)) id = '';
    if (!SLUG_RE.test(slug)) slug = '';

    if (!id && !slug && req.url) {
      const parts = req.url.split('?')[0].split('/').filter(Boolean);
      const last = (parts[parts.length - 1] || '').trim();
      const prev = parts[parts.length - 2] || '';
      if (UUID_RE.test(last)) id = last;
      else if (prev === 's' && SLUG_RE.test(last.toLowerCase())) slug = last.toLowerCase();
    }

    // Send exactly ONE key. Sending both would let a mismatched pair
    // resolve to whichever the edge function happened to check first,
    // which is how a dealer's short link quietly renders someone else's
    // shop. An empty id is forwarded deliberately: the edge function
    // owns the "not found" page, so there is one copy of that wording.
    const query = slug
      ? `slug=${encodeURIComponent(slug)}`
      : `id=${encodeURIComponent(id)}`;

    const upstream = await fetch(`${SELLER_PREVIEW_URL}?${query}`, {
      headers: { Accept: 'text/html' },
    });

    const html = await upstream.text();

    // The whole reason this file exists.
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    res.setHeader('Cache-Control', 'public, max-age=300, s-maxage=300');
    res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');

    return res.status(upstream.status).send(html);
  } catch (err) {
    console.error('api/seller failed:', err);
    // Never leave a share link showing a raw stack trace — degrade to a
    // plain, correctly-typed page that still points somewhere useful.
    res.setHeader('Content-Type', 'text/html; charset=utf-8');
    return res
      .status(502)
      .send(
        '<!DOCTYPE html><html lang="en"><head><meta charset="utf-8">' +
          '<title>ImbizoHub</title><meta name="robots" content="noindex">' +
          '<style>body{background:#111;color:#fff;font-family:-apple-system,Roboto,Arial,sans-serif;' +
          'text-align:center;padding:48px 20px}a{color:#E8B44A}</style></head>' +
          '<body><h1>Something went wrong</h1>' +
          '<p>We could not load this profile just now.</p>' +
          '<p><a href="https://imbizohub.com">Go to ImbizoHub</a></p></body></html>'
      );
  }
};
